name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.5
  audioplayers: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/main_bgm.mp3
    - assets/mainButton_click.mp3
    - assets/secButton_click.mp3
    - assets/selection_click.mp3
    - assets/pauseButton_click.mp3
    - assets/backButton_click.mp3
    - assets/countdown_launch.mp3
    - assets/space_travel.mp3
    - assets/laser_shoot.mp3
    - assets/correct_answer.mp3
    - assets/wrong_answer.mp3
    - assets/mission_accomplished.mp3
    - assets/claim.mp3
    - assets/mission_failed.mp3
    
    - images/1Avatar.png
    - images/2Avatar.png
    - images/3Avatar.png
    - images/4Avatar.png
    - images/5Avatar.png
    - images/6Avatar.png
    # - images/7Avatar.png
    - images/AvatarAlien.png

    - images/icon.png
    - images/transicon.png
    - images/alien.png
    
    - images/earth.png
    - images/mercury.png
    - images/venus.png
    - images/mars.png
    - images/jupiter.png
    - images/saturn.png
    - images/uranus.png
    - images/neptune.png
    - images/sun.png

    - images/rocket1.png
    - images/rocket2.png
    - images/rocket3.png
    - images/rocket4.png
    - images/rocket5.png
    - images/rocket6.png
    - images/rocket7.png
    - images/rocket8.png
    
    - images/premium1.png
    - images/premium2.png
    - images/premium3.png
    - images/extralives2.png
    - images/extralives3.png
    - images/extralives5.png

    - images/asteroid0.png
    - images/asteroid1.png
    - images/asteroid2.png

  fonts:
    - family: Michroma
      fonts:
        - asset: fonts/Michroma-Regular.ttf
    - family: Russo One
      fonts:
        - asset: fonts/RussoOne-Regular.ttf
    - family: Exo 2
      fonts:
        - asset: fonts/Exo2-VariableFont_wght.ttf
    - family: Share-Tech
      fonts:
        - asset: fonts/ShareTech-Regular.ttf