name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.5
  audioplayers: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "images/icon.png"

flutter:
  uses-material-design: true

  assets:
    # -------------- Narration on Solo Planet Info
    -assets/narration/-sun_basic.mp3
    -assets/narration/-sun_intermediate.mp3
    -assets/narration/-sun_advanced.mp3
    -assets/narration/-mercury_basic.mp3
    -assets/narration/-mercury_intermediate.mp3
    -assets/narration/-mercury_advanced.mp3
    -assets/narration/-venus_basic.mp3
    -assets/narration/-venus_intermediate.mp3
    -assets/narration/-venus_advanced.mp3
    -assets/narration/-earth_basic.mp3
    -assets/narration/-earth_intermediate.mp3
    -assets/narration/-earth_advanced.mp3
    -assets/narration/-mars_basic.mp3
    -assets/narration/-mars_intermediate.mp3
    -assets/narration/-mars_advanced.mp3
    -assets/narration/-jupiter_basic.mp3
    -assets/narration/-jupiter_intermediate.mp3
    -assets/narration/-jupiter_advanced.mp3
    -assets/narration/-saturn_basic.mp3
    -assets/narration/-saturn_intermediate.mp3
    -assets/narration/-saturn_advanced.mp3
    -assets/narration/-uranus_basic.mp3
    -assets/narration/-uranus_intermediate.mp3
    -assets/narration/-uranus_advanced.mp3
    -assets/narration/-neptune_basic.mp3
    -assets/narration/-neptune_intermediate.mp3
    -assets/narration/-neptune_advanced.mp3

    -assets/narration/sun_basic_q1
    -assets/narration/sun_basic_q2
    -assets/narration/sun_basic_q3
    -assets/narration/sun_basic_q4
    -assets/narration/sun_basic_q5
    -assets/narration/sun_basic_q6
    -assets/narration/sun_basic_q7
    -assets/narration/sun_basic_q8
    -assets/narration/sun_basic_q9
    -assets/narration/sun_basic_q10
    -assets/narration/sun_intermediate_q1
    -assets/narration/sun_intermediate_q2
    -assets/narration/sun_intermediate_q3
    -assets/narration/sun_intermediate_q4
    -assets/narration/sun_intermediate_q5
    -assets/narration/sun_intermediate_q6
    -assets/narration/sun_intermediate_q7
    -assets/narration/sun_intermediate_q8
    -assets/narration/sun_intermediate_q9
    -assets/narration/sun_intermediate_q10
    -assets/narration/sun_advanced_q1
    -assets/narration/sun_advanced_q2
    -assets/narration/sun_advanced_q3
    -assets/narration/sun_advanced_q4
    -assets/narration/sun_advanced_q5
    -assets/narration/sun_advanced_q6
    -assets/narration/sun_advanced_q7
    -assets/narration/sun_advanced_q8
    -assets/narration/sun_advanced_q9
    -assets/narration/sun_advanced_q10

    -assets/narration/mercury_basic_q1
    -assets/narration/mercury_basic_q2
    -assets/narration/mercury_basic_q3
    -assets/narration/mercury_basic_q4
    -assets/narration/mercury_basic_q5
    -assets/narration/mercury_basic_q6
    -assets/narration/mercury_basic_q7
    -assets/narration/mercury_basic_q8
    -assets/narration/mercury_basic_q9
    -assets/narration/mercury_basic_q10
    -assets/narration/mercury_intermediate_q1
    -assets/narration/mercury_intermediate_q2
    -assets/narration/mercury_intermediate_q3
    -assets/narration/mercury_intermediate_q4
    -assets/narration/mercury_intermediate_q5
    -assets/narration/mercury_intermediate_q6
    -assets/narration/mercury_intermediate_q7
    -assets/narration/mercury_intermediate_q8
    -assets/narration/mercury_intermediate_q9
    -assets/narration/mercury_intermediate_q10
    -assets/narration/mercury_advanced_q1
    -assets/narration/mercury_advanced_q2
    -assets/narration/mercury_advanced_q3
    -assets/narration/mercury_advanced_q4
    -assets/narration/mercury_advanced_q5
    -assets/narration/mercury_advanced_q6
    -assets/narration/mercury_advanced_q7
    -assets/narration/mercury_advanced_q8
    -assets/narration/mercury_advanced_q9
    -assets/narration/mercury_advanced_q10

    -assets/narration/venus_basic_q1
    -assets/narration/venus_basic_q2
    -assets/narration/venus_basic_q3
    -assets/narration/venus_basic_q4
    -assets/narration/venus_basic_q5
    -assets/narration/venus_basic_q6
    -assets/narration/venus_basic_q7
    -assets/narration/venus_basic_q8
    -assets/narration/venus_basic_q9
    -assets/narration/venus_basic_q10
    -assets/narration/venus_intermediate_q1
    -assets/narration/venus_intermediate_q2
    -assets/narration/venus_intermediate_q3
    -assets/narration/venus_intermediate_q4
    -assets/narration/venus_intermediate_q5
    -assets/narration/venus_intermediate_q6
    -assets/narration/venus_intermediate_q7
    -assets/narration/venus_intermediate_q8
    -assets/narration/venus_intermediate_q9
    -assets/narration/venus_intermediate_q10
    -assets/narration/venus_advanced_q1
    -assets/narration/venus_advanced_q2
    -assets/narration/venus_advanced_q3
    -assets/narration/venus_advanced_q4
    -assets/narration/venus_advanced_q5
    -assets/narration/venus_advanced_q6
    -assets/narration/venus_advanced_q7
    -assets/narration/venus_advanced_q8
    -assets/narration/venus_advanced_q9
    -assets/narration/venus_advanced_q10

    -assets/narration/earth_basic_q1
    -assets/narration/earth_basic_q2
    -assets/narration/earth_basic_q3
    -assets/narration/earth_basic_q4
    -assets/narration/earth_basic_q5
    -assets/narration/earth_basic_q6
    -assets/narration/earth_basic_q7
    -assets/narration/earth_basic_q8
    -assets/narration/earth_basic_q9
    -assets/narration/earth_basic_q10
    -assets/narration/earth_intermediate_q1
    -assets/narration/earth_intermediate_q2
    -assets/narration/earth_intermediate_q3
    -assets/narration/earth_intermediate_q4
    -assets/narration/earth_intermediate_q5
    -assets/narration/earth_intermediate_q6
    -assets/narration/earth_intermediate_q7
    -assets/narration/earth_intermediate_q8
    -assets/narration/earth_intermediate_q9
    -assets/narration/earth_intermediate_q10
    -assets/narration/earth_advanced_q1
    -assets/narration/earth_advanced_q2
    -assets/narration/earth_advanced_q3
    -assets/narration/earth_advanced_q4
    -assets/narration/earth_advanced_q5
    -assets/narration/earth_advanced_q6
    -assets/narration/earth_advanced_q7
    -assets/narration/earth_advanced_q8
    -assets/narration/earth_advanced_q9
    -assets/narration/earth_advanced_q10

    -assets/narration/mars_basic_q1
    -assets/narration/mars_basic_q2
    -assets/narration/mars_basic_q3
    -assets/narration/mars_basic_q4
    -assets/narration/mars_basic_q5
    -assets/narration/mars_basic_q6
    -assets/narration/mars_basic_q7
    -assets/narration/mars_basic_q8
    -assets/narration/mars_basic_q9
    -assets/narration/mars_basic_q10
    -assets/narration/mars_intermediate_q1
    -assets/narration/mars_intermediate_q2
    -assets/narration/mars_intermediate_q3
    -assets/narration/mars_intermediate_q4
    -assets/narration/mars_intermediate_q5
    -assets/narration/mars_intermediate_q6
    -assets/narration/mars_intermediate_q7
    -assets/narration/mars_intermediate_q8
    -assets/narration/mars_intermediate_q9
    -assets/narration/mars_intermediate_q10
    -assets/narration/mars_advanced_q1
    -assets/narration/mars_advanced_q2
    -assets/narration/mars_advanced_q3
    -assets/narration/mars_advanced_q4
    -assets/narration/mars_advanced_q5
    -assets/narration/mars_advanced_q6
    -assets/narration/mars_advanced_q7
    -assets/narration/mars_advanced_q8
    -assets/narration/mars_advanced_q9
    -assets/narration/mars_advanced_q10

    -assets/narration/jupiter_basic_q1
    -assets/narration/jupiter_basic_q2
    -assets/narration/jupiter_basic_q3
    -assets/narration/jupiter_basic_q4
    -assets/narration/jupiter_basic_q5
    -assets/narration/jupiter_basic_q6
    -assets/narration/jupiter_basic_q7
    -assets/narration/jupiter_basic_q8
    -assets/narration/jupiter_basic_q9
    -assets/narration/jupiter_basic_q10
    -assets/narration/jupiter_intermediate_q1
    -assets/narration/jupiter_intermediate_q2
    -assets/narration/jupiter_intermediate_q3
    -assets/narration/jupiter_intermediate_q4
    -assets/narration/jupiter_intermediate_q5
    -assets/narration/jupiter_intermediate_q6
    -assets/narration/jupiter_intermediate_q7
    -assets/narration/jupiter_intermediate_q8
    -assets/narration/jupiter_intermediate_q9
    -assets/narration/jupiter_intermediate_q10
    -assets/narration/jupiter_advanced_q1
    -assets/narration/jupiter_advanced_q2
    -assets/narration/jupiter_advanced_q3
    -assets/narration/jupiter_advanced_q4
    -assets/narration/jupiter_advanced_q5
    -assets/narration/jupiter_advanced_q6
    -assets/narration/jupiter_advanced_q7
    -assets/narration/jupiter_advanced_q8
    -assets/narration/jupiter_advanced_q9
    -assets/narration/jupiter_advanced_q10

    -assets/narration/saturn_basic_q1
    -assets/narration/saturn_basic_q2
    -assets/narration/saturn_basic_q3
    -assets/narration/saturn_basic_q4
    -assets/narration/saturn_basic_q5
    -assets/narration/saturn_basic_q6
    -assets/narration/saturn_basic_q7
    -assets/narration/saturn_basic_q8
    -assets/narration/saturn_basic_q9
    -assets/narration/saturn_basic_q10
    -assets/narration/saturn_intermediate_q1
    -assets/narration/saturn_intermediate_q2
    -assets/narration/saturn_intermediate_q3
    -assets/narration/saturn_intermediate_q4
    -assets/narration/saturn_intermediate_q5
    -assets/narration/saturn_intermediate_q6
    -assets/narration/saturn_intermediate_q7
    -assets/narration/saturn_intermediate_q8
    -assets/narration/saturn_intermediate_q9
    -assets/narration/saturn_intermediate_q10
    -assets/narration/saturn_advanced_q1
    -assets/narration/saturn_advanced_q2
    -assets/narration/saturn_advanced_q3
    -assets/narration/saturn_advanced_q4
    -assets/narration/saturn_advanced_q5
    -assets/narration/saturn_advanced_q6
    -assets/narration/saturn_advanced_q7
    -assets/narration/saturn_advanced_q8
    -assets/narration/saturn_advanced_q9
    -assets/narration/saturn_advanced_q10

    -assets/narration/uranus_basic_q1
    -assets/narration/uranus_basic_q2
    -assets/narration/uranus_basic_q3
    -assets/narration/uranus_basic_q4
    -assets/narration/uranus_basic_q5
    -assets/narration/uranus_basic_q6
    -assets/narration/uranus_basic_q7
    -assets/narration/uranus_basic_q8
    -assets/narration/uranus_basic_q9
    -assets/narration/uranus_basic_q10
    -assets/narration/uranus_intermediate_q1
    -assets/narration/uranus_intermediate_q2
    -assets/narration/uranus_intermediate_q3
    -assets/narration/uranus_intermediate_q4
    -assets/narration/uranus_intermediate_q5
    -assets/narration/uranus_intermediate_q6
    -assets/narration/uranus_intermediate_q7
    -assets/narration/uranus_intermediate_q8
    -assets/narration/uranus_intermediate_q9
    -assets/narration/uranus_intermediate_q10
    -assets/narration/uranus_advanced_q1
    -assets/narration/uranus_advanced_q2
    -assets/narration/uranus_advanced_q3
    -assets/narration/uranus_advanced_q4
    -assets/narration/uranus_advanced_q5
    -assets/narration/uranus_advanced_q6
    -assets/narration/uranus_advanced_q7
    -assets/narration/uranus_advanced_q8
    -assets/narration/uranus_advanced_q9
    -assets/narration/uranus_advanced_q10

    -assets/narration/neptune_basic_q1
    -assets/narration/neptune_basic_q2
    -assets/narration/neptune_basic_q3
    -assets/narration/neptune_basic_q4
    -assets/narration/neptune_basic_q5
    -assets/narration/neptune_basic_q6
    -assets/narration/neptune_basic_q7
    -assets/narration/neptune_basic_q8
    -assets/narration/neptune_basic_q9
    -assets/narration/neptune_basic_q10
    -assets/narration/neptune_intermediate_q1
    -assets/narration/neptune_intermediate_q2
    -assets/narration/neptune_intermediate_q3
    -assets/narration/neptune_intermediate_q4
    -assets/narration/neptune_intermediate_q5
    -assets/narration/neptune_intermediate_q6
    -assets/narration/neptune_intermediate_q7
    -assets/narration/neptune_intermediate_q8
    -assets/narration/neptune_intermediate_q9
    -assets/narration/neptune_intermediate_q10
    -assets/narration/neptune_advanced_q1
    -assets/narration/neptune_advanced_q2
    -assets/narration/neptune_advanced_q3
    -assets/narration/neptune_advanced_q4
    -assets/narration/neptune_advanced_q5
    -assets/narration/neptune_advanced_q6
    -assets/narration/neptune_advanced_q7
    -assets/narration/neptune_advanced_q8
    -assets/narration/neptune_advanced_q9
    -assets/narration/neptune_advanced_q10


    - assets/main_bgm.mp3
    - assets/mainButton_click.mp3
    - assets/secButton_click.mp3
    - assets/selection_click.mp3
    - assets/pauseButton_click.mp3
    - assets/backButton_click.mp3
    - assets/launch_splashscreen.mp3
    - assets/space_travel.mp3
    - assets/laser_shoot.mp3
    - assets/correct_answer.mp3
    - assets/wrong_answer.mp3
    - assets/mission_accomplished.mp3
    - assets/claim.mp3
    - assets/mission_failed.mp3
    
    - images/1Avatar.png
    - images/2Avatar.png
    - images/3Avatar.png
    - images/4Avatar.png
    - images/5Avatar.png
    - images/6Avatar.png
    - images/7Avatar.png
    - images/AvatarAlien.png

    - images/icon.png
    - images/transicon.png
    - images/alien.png
    
    - images/earth.png
    - images/mercury.png
    - images/venus.png
    - images/mars.png
    - images/jupiter.png
    - images/saturn.png
    - images/uranus.png
    - images/neptune.png
    - images/sun.png

    - images/rocket1.png
    - images/rocket2.png
    - images/rocket3.png
    - images/rocket4.png
    - images/rocket5.png
    - images/rocket6.png
    - images/rocket7.png
    - images/rocket8.png
    
    - images/premium1.png
    - images/premium2.png
    - images/premium3.png
    - images/extralives2.png
    - images/extralives3.png
    - images/extralives5.png

    - images/asteroid0.png
    - images/asteroid1.png
    - images/asteroid2.png

  fonts:
    - family: Michroma
      fonts:
        - asset: fonts/Michroma-Regular.ttf
    - family: Russo One
      fonts:
        - asset: fonts/RussoOne-Regular.ttf
    - family: Exo 2
      fonts:
        - asset: fonts/Exo2-VariableFont_wght.ttf
    - family: Share-Tech
      fonts:
        - asset: fonts/ShareTech-Regular.ttf